//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2Soft.NegocioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", ConfigurationName="NegocioWS.NegocioWS")]
    public interface NegocioWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.insertarProductoResponse insertarProducto(LP2Soft.NegocioWS.insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarProductoResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarProductoResponse> insertarProductoAsync(LP2Soft.NegocioWS.insertarProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.eliminarProductoResponse eliminarProducto(LP2Soft.NegocioWS.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarProductoResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarProductoResponse> eliminarProductoAsync(LP2Soft.NegocioWS.eliminarProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarCategoriaRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.modificarCategoriaResponse modificarCategoria(LP2Soft.NegocioWS.modificarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarCategoriaRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarCategoriaResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarCategoriaResponse> modificarCategoriaAsync(LP2Soft.NegocioWS.modificarCategoriaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarPromocionRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarPromocionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.insertarPromocionResponse insertarPromocion(LP2Soft.NegocioWS.insertarPromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarPromocionRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarPromocionResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarPromocionResponse> insertarPromocionAsync(LP2Soft.NegocioWS.insertarPromocionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarCategoriaRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.insertarCategoriaResponse insertarCategoria(LP2Soft.NegocioWS.insertarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarCategoriaRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/insertarCategoriaResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarCategoriaResponse> insertarCategoriaAsync(LP2Soft.NegocioWS.insertarCategoriaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasCategoriasRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasCategoriasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.listarTodasCategoriasResponse listarTodasCategorias(LP2Soft.NegocioWS.listarTodasCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasCategoriasRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasCategoriasResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodasCategoriasResponse> listarTodasCategoriasAsync(LP2Soft.NegocioWS.listarTodasCategoriasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarPromocionRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarPromocionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.modificarPromocionResponse modificarPromocion(LP2Soft.NegocioWS.modificarPromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarPromocionRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarPromocionResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarPromocionResponse> modificarPromocionAsync(LP2Soft.NegocioWS.modificarPromocionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasPromocionesRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasPromocionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.listarTodasPromocionesResponse listarTodasPromociones(LP2Soft.NegocioWS.listarTodasPromocionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasPromocionesRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodasPromocionesResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodasPromocionesResponse> listarTodasPromocionesAsync(LP2Soft.NegocioWS.listarTodasPromocionesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodosProductosRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodosProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.listarTodosProductosResponse listarTodosProductos(LP2Soft.NegocioWS.listarTodosProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodosProductosRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarTodosProductosResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodosProductosResponse> listarTodosProductosAsync(LP2Soft.NegocioWS.listarTodosProductosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.modificarProductoResponse modificarProducto(LP2Soft.NegocioWS.modificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarProductoRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/modificarProductoResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarProductoResponse> modificarProductoAsync(LP2Soft.NegocioWS.modificarProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarPromocionRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarPromocionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.eliminarPromocionResponse eliminarPromocion(LP2Soft.NegocioWS.eliminarPromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarPromocionRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarPromocionResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarPromocionResponse> eliminarPromocionAsync(LP2Soft.NegocioWS.eliminarPromocionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarCategoriaRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.eliminarCategoriaResponse eliminarCategoria(LP2Soft.NegocioWS.eliminarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarCategoriaRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/eliminarCategoriaResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarCategoriaResponse> eliminarCategoriaAsync(LP2Soft.NegocioWS.eliminarCategoriaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarProductoXNombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarProductoXNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVendible))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2Soft.NegocioWS.listarProductoXNombreResponse listarProductoXNombre(LP2Soft.NegocioWS.listarProductoXNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarProductoXNombreRequest", ReplyAction="http://services.lp2soft.pucp.edu.pe/NegocioWS/listarProductoXNombreResponse")]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarProductoXNombreResponse> listarProductoXNombreAsync(LP2Soft.NegocioWS.listarProductoXNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class producto : itemVendible {
        
        private categoria categoriaField;
        
        private int idProductoField;
        
        private string presentacionField;
        
        private ushort tipoProductoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string presentacion {
            get {
                return this.presentacionField;
            }
            set {
                this.presentacionField = value;
                this.RaisePropertyChanged("presentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idCategoriaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class lineaPromocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private int idLineaPromocionField;
        
        private producto productoField;
        
        private int unidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaPromocion {
            get {
                return this.idLineaPromocionField;
            }
            set {
                this.idLineaPromocionField = value;
                this.RaisePropertyChanged("idLineaPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
                this.RaisePropertyChanged("unidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(promocion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class itemVendible : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private bool estadoField;
        
        private int idItemVendibleField;
        
        private string nombreField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idItemVendible {
            get {
                return this.idItemVendibleField;
            }
            set {
                this.idItemVendibleField = value;
                this.RaisePropertyChanged("idItemVendible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/")]
    public partial class promocion : itemVendible {
        
        private lineaPromocion[] lista_de_ComidasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lista_de_Comidas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public lineaPromocion[] lista_de_Comidas {
            get {
                return this.lista_de_ComidasField;
            }
            set {
                this.lista_de_ComidasField = value;
                this.RaisePropertyChanged("lista_de_Comidas");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProducto", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.producto Producto;
        
        public insertarProductoRequest() {
        }
        
        public insertarProductoRequest(LP2Soft.NegocioWS.producto Producto) {
            this.Producto = Producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoResponse() {
        }
        
        public insertarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        public eliminarProductoRequest() {
        }
        
        public eliminarProductoRequest(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarProductoResponse() {
        }
        
        public eliminarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCategoria", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.categoria Categoria;
        
        public modificarCategoriaRequest() {
        }
        
        public modificarCategoriaRequest(LP2Soft.NegocioWS.categoria Categoria) {
            this.Categoria = Categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCategoriaResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCategoriaResponse() {
        }
        
        public modificarCategoriaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocion", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.promocion Promocion;
        
        public insertarPromocionRequest() {
        }
        
        public insertarPromocionRequest(LP2Soft.NegocioWS.promocion Promocion) {
            this.Promocion = Promocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocionResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPromocionResponse() {
        }
        
        public insertarPromocionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCategoria", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.categoria Categoria;
        
        public insertarCategoriaRequest() {
        }
        
        public insertarCategoriaRequest(LP2Soft.NegocioWS.categoria Categoria) {
            this.Categoria = Categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCategoriaResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCategoriaResponse() {
        }
        
        public insertarCategoriaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasCategorias", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasCategoriasRequest {
        
        public listarTodasCategoriasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasCategoriasResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.categoria[] @return;
        
        public listarTodasCategoriasResponse() {
        }
        
        public listarTodasCategoriasResponse(LP2Soft.NegocioWS.categoria[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPromocion", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.promocion Promocion;
        
        public modificarPromocionRequest() {
        }
        
        public modificarPromocionRequest(LP2Soft.NegocioWS.promocion Promocion) {
            this.Promocion = Promocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPromocionResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPromocionResponse() {
        }
        
        public modificarPromocionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasPromociones", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasPromocionesRequest {
        
        public listarTodasPromocionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasPromocionesResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasPromocionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.promocion[] @return;
        
        public listarTodasPromocionesResponse() {
        }
        
        public listarTodasPromocionesResponse(LP2Soft.NegocioWS.promocion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosProductos", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosProductosRequest {
        
        public listarTodosProductosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosProductosResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.producto[] @return;
        
        public listarTodosProductosResponse() {
        }
        
        public listarTodosProductosResponse(LP2Soft.NegocioWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProducto", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.producto Producto;
        
        public modificarProductoRequest() {
        }
        
        public modificarProductoRequest(LP2Soft.NegocioWS.producto Producto) {
            this.Producto = Producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarProductoResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarProductoResponse() {
        }
        
        public modificarProductoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocion", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPromocion;
        
        public eliminarPromocionRequest() {
        }
        
        public eliminarPromocionRequest(int idPromocion) {
            this.idPromocion = idPromocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocionResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPromocionResponse() {
        }
        
        public eliminarPromocionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCategoria", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCategoria;
        
        public eliminarCategoriaRequest() {
        }
        
        public eliminarCategoriaRequest(int idCategoria) {
            this.idCategoria = idCategoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCategoriaResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCategoriaResponse() {
        }
        
        public eliminarCategoriaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductoXNombre", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductoXNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarProductoXNombreRequest() {
        }
        
        public listarProductoXNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductoXNombreResponse", WrapperNamespace="http://services.lp2soft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductoXNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.lp2soft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2Soft.NegocioWS.producto[] @return;
        
        public listarProductoXNombreResponse() {
        }
        
        public listarProductoXNombreResponse(LP2Soft.NegocioWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NegocioWSChannel : LP2Soft.NegocioWS.NegocioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NegocioWSClient : System.ServiceModel.ClientBase<LP2Soft.NegocioWS.NegocioWS>, LP2Soft.NegocioWS.NegocioWS {
        
        public NegocioWSClient() {
        }
        
        public NegocioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NegocioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegocioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegocioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.insertarProductoResponse LP2Soft.NegocioWS.NegocioWS.insertarProducto(LP2Soft.NegocioWS.insertarProductoRequest request) {
            return base.Channel.insertarProducto(request);
        }
        
        public int insertarProducto(LP2Soft.NegocioWS.producto Producto) {
            LP2Soft.NegocioWS.insertarProductoRequest inValue = new LP2Soft.NegocioWS.insertarProductoRequest();
            inValue.Producto = Producto;
            LP2Soft.NegocioWS.insertarProductoResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).insertarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarProductoResponse> LP2Soft.NegocioWS.NegocioWS.insertarProductoAsync(LP2Soft.NegocioWS.insertarProductoRequest request) {
            return base.Channel.insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarProductoResponse> insertarProductoAsync(LP2Soft.NegocioWS.producto Producto) {
            LP2Soft.NegocioWS.insertarProductoRequest inValue = new LP2Soft.NegocioWS.insertarProductoRequest();
            inValue.Producto = Producto;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.eliminarProductoResponse LP2Soft.NegocioWS.NegocioWS.eliminarProducto(LP2Soft.NegocioWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProducto(request);
        }
        
        public int eliminarProducto(int idProducto) {
            LP2Soft.NegocioWS.eliminarProductoRequest inValue = new LP2Soft.NegocioWS.eliminarProductoRequest();
            inValue.idProducto = idProducto;
            LP2Soft.NegocioWS.eliminarProductoResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).eliminarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarProductoResponse> LP2Soft.NegocioWS.NegocioWS.eliminarProductoAsync(LP2Soft.NegocioWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarProductoResponse> eliminarProductoAsync(int idProducto) {
            LP2Soft.NegocioWS.eliminarProductoRequest inValue = new LP2Soft.NegocioWS.eliminarProductoRequest();
            inValue.idProducto = idProducto;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).eliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.modificarCategoriaResponse LP2Soft.NegocioWS.NegocioWS.modificarCategoria(LP2Soft.NegocioWS.modificarCategoriaRequest request) {
            return base.Channel.modificarCategoria(request);
        }
        
        public int modificarCategoria(LP2Soft.NegocioWS.categoria Categoria) {
            LP2Soft.NegocioWS.modificarCategoriaRequest inValue = new LP2Soft.NegocioWS.modificarCategoriaRequest();
            inValue.Categoria = Categoria;
            LP2Soft.NegocioWS.modificarCategoriaResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).modificarCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarCategoriaResponse> LP2Soft.NegocioWS.NegocioWS.modificarCategoriaAsync(LP2Soft.NegocioWS.modificarCategoriaRequest request) {
            return base.Channel.modificarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarCategoriaResponse> modificarCategoriaAsync(LP2Soft.NegocioWS.categoria Categoria) {
            LP2Soft.NegocioWS.modificarCategoriaRequest inValue = new LP2Soft.NegocioWS.modificarCategoriaRequest();
            inValue.Categoria = Categoria;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).modificarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.insertarPromocionResponse LP2Soft.NegocioWS.NegocioWS.insertarPromocion(LP2Soft.NegocioWS.insertarPromocionRequest request) {
            return base.Channel.insertarPromocion(request);
        }
        
        public int insertarPromocion(LP2Soft.NegocioWS.promocion Promocion) {
            LP2Soft.NegocioWS.insertarPromocionRequest inValue = new LP2Soft.NegocioWS.insertarPromocionRequest();
            inValue.Promocion = Promocion;
            LP2Soft.NegocioWS.insertarPromocionResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).insertarPromocion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarPromocionResponse> LP2Soft.NegocioWS.NegocioWS.insertarPromocionAsync(LP2Soft.NegocioWS.insertarPromocionRequest request) {
            return base.Channel.insertarPromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarPromocionResponse> insertarPromocionAsync(LP2Soft.NegocioWS.promocion Promocion) {
            LP2Soft.NegocioWS.insertarPromocionRequest inValue = new LP2Soft.NegocioWS.insertarPromocionRequest();
            inValue.Promocion = Promocion;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).insertarPromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.insertarCategoriaResponse LP2Soft.NegocioWS.NegocioWS.insertarCategoria(LP2Soft.NegocioWS.insertarCategoriaRequest request) {
            return base.Channel.insertarCategoria(request);
        }
        
        public int insertarCategoria(LP2Soft.NegocioWS.categoria Categoria) {
            LP2Soft.NegocioWS.insertarCategoriaRequest inValue = new LP2Soft.NegocioWS.insertarCategoriaRequest();
            inValue.Categoria = Categoria;
            LP2Soft.NegocioWS.insertarCategoriaResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).insertarCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarCategoriaResponse> LP2Soft.NegocioWS.NegocioWS.insertarCategoriaAsync(LP2Soft.NegocioWS.insertarCategoriaRequest request) {
            return base.Channel.insertarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.insertarCategoriaResponse> insertarCategoriaAsync(LP2Soft.NegocioWS.categoria Categoria) {
            LP2Soft.NegocioWS.insertarCategoriaRequest inValue = new LP2Soft.NegocioWS.insertarCategoriaRequest();
            inValue.Categoria = Categoria;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).insertarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.listarTodasCategoriasResponse LP2Soft.NegocioWS.NegocioWS.listarTodasCategorias(LP2Soft.NegocioWS.listarTodasCategoriasRequest request) {
            return base.Channel.listarTodasCategorias(request);
        }
        
        public LP2Soft.NegocioWS.categoria[] listarTodasCategorias() {
            LP2Soft.NegocioWS.listarTodasCategoriasRequest inValue = new LP2Soft.NegocioWS.listarTodasCategoriasRequest();
            LP2Soft.NegocioWS.listarTodasCategoriasResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).listarTodasCategorias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodasCategoriasResponse> LP2Soft.NegocioWS.NegocioWS.listarTodasCategoriasAsync(LP2Soft.NegocioWS.listarTodasCategoriasRequest request) {
            return base.Channel.listarTodasCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodasCategoriasResponse> listarTodasCategoriasAsync() {
            LP2Soft.NegocioWS.listarTodasCategoriasRequest inValue = new LP2Soft.NegocioWS.listarTodasCategoriasRequest();
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).listarTodasCategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.modificarPromocionResponse LP2Soft.NegocioWS.NegocioWS.modificarPromocion(LP2Soft.NegocioWS.modificarPromocionRequest request) {
            return base.Channel.modificarPromocion(request);
        }
        
        public int modificarPromocion(LP2Soft.NegocioWS.promocion Promocion) {
            LP2Soft.NegocioWS.modificarPromocionRequest inValue = new LP2Soft.NegocioWS.modificarPromocionRequest();
            inValue.Promocion = Promocion;
            LP2Soft.NegocioWS.modificarPromocionResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).modificarPromocion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarPromocionResponse> LP2Soft.NegocioWS.NegocioWS.modificarPromocionAsync(LP2Soft.NegocioWS.modificarPromocionRequest request) {
            return base.Channel.modificarPromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarPromocionResponse> modificarPromocionAsync(LP2Soft.NegocioWS.promocion Promocion) {
            LP2Soft.NegocioWS.modificarPromocionRequest inValue = new LP2Soft.NegocioWS.modificarPromocionRequest();
            inValue.Promocion = Promocion;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).modificarPromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.listarTodasPromocionesResponse LP2Soft.NegocioWS.NegocioWS.listarTodasPromociones(LP2Soft.NegocioWS.listarTodasPromocionesRequest request) {
            return base.Channel.listarTodasPromociones(request);
        }
        
        public LP2Soft.NegocioWS.promocion[] listarTodasPromociones() {
            LP2Soft.NegocioWS.listarTodasPromocionesRequest inValue = new LP2Soft.NegocioWS.listarTodasPromocionesRequest();
            LP2Soft.NegocioWS.listarTodasPromocionesResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).listarTodasPromociones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodasPromocionesResponse> LP2Soft.NegocioWS.NegocioWS.listarTodasPromocionesAsync(LP2Soft.NegocioWS.listarTodasPromocionesRequest request) {
            return base.Channel.listarTodasPromocionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodasPromocionesResponse> listarTodasPromocionesAsync() {
            LP2Soft.NegocioWS.listarTodasPromocionesRequest inValue = new LP2Soft.NegocioWS.listarTodasPromocionesRequest();
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).listarTodasPromocionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.listarTodosProductosResponse LP2Soft.NegocioWS.NegocioWS.listarTodosProductos(LP2Soft.NegocioWS.listarTodosProductosRequest request) {
            return base.Channel.listarTodosProductos(request);
        }
        
        public LP2Soft.NegocioWS.producto[] listarTodosProductos() {
            LP2Soft.NegocioWS.listarTodosProductosRequest inValue = new LP2Soft.NegocioWS.listarTodosProductosRequest();
            LP2Soft.NegocioWS.listarTodosProductosResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).listarTodosProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodosProductosResponse> LP2Soft.NegocioWS.NegocioWS.listarTodosProductosAsync(LP2Soft.NegocioWS.listarTodosProductosRequest request) {
            return base.Channel.listarTodosProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarTodosProductosResponse> listarTodosProductosAsync() {
            LP2Soft.NegocioWS.listarTodosProductosRequest inValue = new LP2Soft.NegocioWS.listarTodosProductosRequest();
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).listarTodosProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.modificarProductoResponse LP2Soft.NegocioWS.NegocioWS.modificarProducto(LP2Soft.NegocioWS.modificarProductoRequest request) {
            return base.Channel.modificarProducto(request);
        }
        
        public int modificarProducto(LP2Soft.NegocioWS.producto Producto) {
            LP2Soft.NegocioWS.modificarProductoRequest inValue = new LP2Soft.NegocioWS.modificarProductoRequest();
            inValue.Producto = Producto;
            LP2Soft.NegocioWS.modificarProductoResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).modificarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarProductoResponse> LP2Soft.NegocioWS.NegocioWS.modificarProductoAsync(LP2Soft.NegocioWS.modificarProductoRequest request) {
            return base.Channel.modificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.modificarProductoResponse> modificarProductoAsync(LP2Soft.NegocioWS.producto Producto) {
            LP2Soft.NegocioWS.modificarProductoRequest inValue = new LP2Soft.NegocioWS.modificarProductoRequest();
            inValue.Producto = Producto;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).modificarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.eliminarPromocionResponse LP2Soft.NegocioWS.NegocioWS.eliminarPromocion(LP2Soft.NegocioWS.eliminarPromocionRequest request) {
            return base.Channel.eliminarPromocion(request);
        }
        
        public int eliminarPromocion(int idPromocion) {
            LP2Soft.NegocioWS.eliminarPromocionRequest inValue = new LP2Soft.NegocioWS.eliminarPromocionRequest();
            inValue.idPromocion = idPromocion;
            LP2Soft.NegocioWS.eliminarPromocionResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).eliminarPromocion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarPromocionResponse> LP2Soft.NegocioWS.NegocioWS.eliminarPromocionAsync(LP2Soft.NegocioWS.eliminarPromocionRequest request) {
            return base.Channel.eliminarPromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarPromocionResponse> eliminarPromocionAsync(int idPromocion) {
            LP2Soft.NegocioWS.eliminarPromocionRequest inValue = new LP2Soft.NegocioWS.eliminarPromocionRequest();
            inValue.idPromocion = idPromocion;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).eliminarPromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.eliminarCategoriaResponse LP2Soft.NegocioWS.NegocioWS.eliminarCategoria(LP2Soft.NegocioWS.eliminarCategoriaRequest request) {
            return base.Channel.eliminarCategoria(request);
        }
        
        public int eliminarCategoria(int idCategoria) {
            LP2Soft.NegocioWS.eliminarCategoriaRequest inValue = new LP2Soft.NegocioWS.eliminarCategoriaRequest();
            inValue.idCategoria = idCategoria;
            LP2Soft.NegocioWS.eliminarCategoriaResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).eliminarCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarCategoriaResponse> LP2Soft.NegocioWS.NegocioWS.eliminarCategoriaAsync(LP2Soft.NegocioWS.eliminarCategoriaRequest request) {
            return base.Channel.eliminarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.eliminarCategoriaResponse> eliminarCategoriaAsync(int idCategoria) {
            LP2Soft.NegocioWS.eliminarCategoriaRequest inValue = new LP2Soft.NegocioWS.eliminarCategoriaRequest();
            inValue.idCategoria = idCategoria;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).eliminarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2Soft.NegocioWS.listarProductoXNombreResponse LP2Soft.NegocioWS.NegocioWS.listarProductoXNombre(LP2Soft.NegocioWS.listarProductoXNombreRequest request) {
            return base.Channel.listarProductoXNombre(request);
        }
        
        public LP2Soft.NegocioWS.producto[] listarProductoXNombre(string nombre) {
            LP2Soft.NegocioWS.listarProductoXNombreRequest inValue = new LP2Soft.NegocioWS.listarProductoXNombreRequest();
            inValue.nombre = nombre;
            LP2Soft.NegocioWS.listarProductoXNombreResponse retVal = ((LP2Soft.NegocioWS.NegocioWS)(this)).listarProductoXNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarProductoXNombreResponse> LP2Soft.NegocioWS.NegocioWS.listarProductoXNombreAsync(LP2Soft.NegocioWS.listarProductoXNombreRequest request) {
            return base.Channel.listarProductoXNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2Soft.NegocioWS.listarProductoXNombreResponse> listarProductoXNombreAsync(string nombre) {
            LP2Soft.NegocioWS.listarProductoXNombreRequest inValue = new LP2Soft.NegocioWS.listarProductoXNombreRequest();
            inValue.nombre = nombre;
            return ((LP2Soft.NegocioWS.NegocioWS)(this)).listarProductoXNombreAsync(inValue);
        }
    }
}
